export const TIMING_CONSTANTS = {
  DEBOUNCE_SEARCH_MS: 300,
  DEBOUNCE_INPUT_MS: 200,
  TOAST_AUTO_CLOSE_MS: 2000,
  TOAST_SUCCESS_CLOSE_MS: 3000,
  ANIMATION_DELAY_SHORT_MS: 100,
  ANIMATION_DELAY_MEDIUM_MS: 500,
  ANIMATION_DELAY_LONG_MS: 800,
  ANIMATION_DELAY_VERY_LONG_MS: 1500,
  AUTO_REFRESH_INTERVAL_MS: 30000,
  PERFORMANCE_REFRESH_MS: 5000,
  MONITOR_UPDATE_INTERVAL_MS: 60000,
  FILE_UPLOAD_RESET_DELAY_MS: 1000,
  NAVIGATION_DELAY_MS: 500,
  URL_REVOKE_DELAY_MS: 1000,
  PAGE_RELOAD_DELAY_MS: 1500,
} as const;

export const UI_CONSTANTS = {
  VIRTUAL_SCROLL_THRESHOLD: 50,
  MAX_LEGEND_ITEMS: 6,
  MAX_MIGRATION_HISTORY_ITEMS: 50,
  TOP_LARGEST_ITEMS_CLEANUP: 10,
  DEFAULT_PAGE_SIZE: 20,
  SIDEBAR_WIDTH_COLLAPSED: 64,
  SIDEBAR_WIDTH_EXPANDED: 256,
  MODAL_MAX_HEIGHT_PERCENT: 90,
  DROPDOWN_MIN_WIDTH: 140,
  TOOLTIP_DELAY_MS: 200,
} as const;

export const STORAGE_QUOTA_THRESHOLDS = {
  CRITICAL_PERCENT: 90,
  WARNING_PERCENT: 75,
  CAUTION_PERCENT: 50,
} as const;

export const HEALTH_SCORE_PENALTIES = {
  CRITICAL_USAGE: 30,
  WARNING_USAGE: 15,
  CAUTION_USAGE: 5,
} as const;

export const STAGE_ARRAY = ['F阶段', 'C阶段', 'S阶段', 'D阶段', 'P阶段'] as const;
export type ProjectStage = typeof STAGE_ARRAY[number];
