export type ProjectStage = 'F阶段' | 'C阶段' | 'S阶段' | 'D阶段' | 'P阶段';

export type ModuleStatus = '未投产' | '投产中' | '正常' | '维修中' | '三防中' | '测试中' | '仿真中' | '借用中' | '故障';
export type ComponentStatus = '未投产' | '投产中' | '正常' | '维修中' | '三防中' | '测试中' | '仿真中' | '借用中' | '故障';
export type DocumentStatus = '未完成' | '已完成';
export type SoftwareStatus = '未完成' | '已完成';
export type TaskStatus = '进行中' | '已完成' | '已过期';

export type UserRole = 'admin' | 'manager' | 'engineer' | 'viewer';

export type CertificateStatus = '未签署' | '已签署';

export interface AssemblyCertificate {
  status: CertificateStatus;
  signedAt?: string;
  signedBy?: string;
}

export interface ComponentCertificates {
  pcb?: CertificateStatus;
  assembly?: CertificateStatus;
  coating?: CertificateStatus;
  final?: CertificateStatus;
}

export interface StatusChange {
  id: string;
  fromStatus: string;
  toStatus: string;
  changedAt: string;
  changedBy: string;
  reason?: string;
}

export interface ProjectLog {
  id: string;
  action: string;
  timestamp: string;
  userId: string;
  username: string;
  details?: string;
}

export interface ModuleLog {
  id: string;
  action: string;
  timestamp: string;
  userId: string;
  username: string;
  details?: string;
}

export interface ComponentLog {
  id: string;
  action: string;
  timestamp: string;
  userId: string;
  username: string;
  details?: string;
}

export interface Document {
  id: string;
  name: string;
  type: string;
  stage: ProjectStage;
  status: DocumentStatus;
  fileUrl?: string;
  fileName?: string;
  fileSize?: number;
  uploadDate?: string;
  completionDate?: string;
  dbId?: string;
}

export interface Software {
  id: string;
  name: string;
  version: string;
  stage: ProjectStage;
  status: SoftwareStatus;
  fileUrl?: string;
  fileName?: string;
  fileSize?: number;
  md5?: string;
  uploadDate?: string;
  completionDate?: string;
  productionOrderNumber?: string;
  固化日期?: string;
  固化指令号?: string[];
  adaptedCategories?: string[];
  adaptedComponentTypes?: string[];
  adaptedComponentIds?: string[];
  adaptedComponents?: { id: string; name: string }[];
  dbId?: string;
}

export interface DesignFile {
  id: string;
  name: string;
  type: '配套表' | '装配图';
  format: 'Excel' | 'AutoCAD' | 'PDF';
  category?: string;
  moduleId?: string;
  componentId?: string;
  stage?: ProjectStage;
  version?: string;
  isAutoGenerated: boolean;
  uploadDate: string;
  fileUrl?: string;
  fileName?: string;
  data?: string;
  fileSize?: number;
  fileType?: string;
}

export interface Component {
  id: string;
  moduleId: string;
  componentNumber: string;
  componentName: string;
  productionOrderNumber: string;
  repairOrderNumber?: string;
  protectionOrderNumber?: string;
  holder?: string;
  stage?: string;
  version?: string;
  status: ComponentStatus;
  logs: ComponentLog[];
  certificates: ComponentCertificates;
  statusChanges: StatusChange[];
  designFiles?: string[];
  burnedSoftware?: BurnedSoftware[];
}

export interface BurnedSoftware {
  id: string;
  softwareId: string;
  softwareName: string;
  softwareVersion: string;
  burnedAt: string;
  burnedBy: string;
}

export interface Module {
  id: string;
  projectId: string;
  systemId?: string;
  productionOrderNumber: string;
  moduleNumber: string;
  moduleName: string;
  category: string;
  holder?: string;
  status: ModuleStatus;
  stage: string;
  version: string;
  productionNumber?: string;
  components: Component[];
  logs: ModuleLog[];
  statusChanges: StatusChange[];
  designFiles?: string[];
  assemblyCertificate?: AssemblyCertificate;
}

export type SystemStatus = '未投产' | '投产中' | '正常' | '维修中' | '三防中' | '测试中' | '仿真中' | '借用中' | '故障';

export interface SystemLog {
  id: string;
  action: string;
  timestamp: string;
  userId: string;
  username: string;
  details?: string;
}

export interface System {
  id: string;
  projectId: string;
  systemNumber: string;
  systemName: string;
  instructionNumber: string;
  stage: ProjectStage;
  status: SystemStatus;
  holder?: string;
  version?: string;
  logs: SystemLog[];
  statusChanges: StatusChange[];
  createdAt?: string;
}

export interface Project {
  id: string;
  name: string;
  projectNumber: string;
  stage: ProjectStage;
  version: string;
  categories: string[];
  modules: Module[];
  systems: System[];
  documents: Document[];
  software: Software[];
  designFiles: DesignFile[];
  logs: ProjectLog[];
  image?: string;
  createdAt?: string;
}

export interface Task {
  id: string;
  title: string;
  description?: string;
  priority: '低' | '中' | '高' | '紧急';
  status: TaskStatus;
  dueDate?: string;
  relatedComponentIds?: string[];
  relatedDocumentIds?: string[];
  createdAt: string;
  completedAt?: string;
}

export interface BorrowRecord {
  id: string;
  itemType: 'module' | 'component';
  itemId: string;
  itemName: string;
  borrower: string;
  borrowDate: string;
  expectedReturnDate?: string;
  actualReturnDate?: string;
  status: '借用中' | '已归还';
  notes?: string;
}
