import React, { useState, useMemo, useCallback, useRef } from 'react';
import {
  FileText, Edit2, Upload, RefreshCw, Download, Trash2, Layout, FileCode, Table,
  Sparkles, X, CheckCircle, AlertCircle, File, Loader2, Plus, Search, FileSearch
} from 'lucide-react';
import { useThemeStyles } from '../../../hooks/useThemeStyles';
import { useToast } from '../../../components/Toast';
import type { ProjectStage, Module, Component } from '../../../types';
import { getDefaultStageForEntity } from '../../../services/stageConfig';

interface DesignFileVersion {
  version: string;
  createdAt: string;
  createdBy?: string;
  note?: string;
}

interface DesignFile {
  id: string;
  name: string;
  type: '装配图' | '配套表';
  format: 'AutoCAD' | 'Excel' | 'PDF';
  category: 'module' | 'component';
  stage?: string;
  version: string;
  uploadDate: string;
  fileSize?: number;
  data?: string;
  adaptedModuleIds?: string[];
  adaptedComponentIds?: string[];
  isAutoGenerated?: boolean;
  moduleId?: string;
  componentId?: string;
  file?: File;
  previewUrl?: string;
  versionHistory?: DesignFileVersion[];
}

interface DesignFilesProps {
  projectId: string;
  designFiles: DesignFile[];
  modules: Module[];
  canEdit: boolean;
  filterCategory: 'all' | 'module' | 'component';
  filterType: 'all' | 'assembly' | 'table';
  filterStage: string;
  filterVersion: string;
  onFilterCategoryChange: (v: 'all' | 'module' | 'component') => void;
  onFilterTypeChange: (v: 'all' | 'assembly' | 'table') => void;
  onFilterStageChange: (v: string) => void;
  onFilterVersionChange: (v: string) => void;
  onResetFilters: () => void;
  onAutoGenerate: () => void;
  onUpload: (e: React.ChangeEvent<HTMLInputElement>, designFileId: string) => void;
  onSync: (file: DesignFile) => void;
  onDelete: (fileId: string) => void;
  onEditFile?: (file: DesignFile) => void;
  onCreateSingle: (options: CreateDesignOptions) => void;
  onVersionUpdate?: (file: DesignFile) => void;
}

interface CreateDesignOptions {
  targetType: 'module' | 'component';
  targetId: string;
  fileType: '装配图' | '配套表';
  format: 'AutoCAD' | 'Excel';
}

const ACCEPTED_FORMATS = {
  AutoCAD: ['.dwg', '.dxf', '.dwt', '.dws'],
  Excel: ['.xlsx', '.xls', '.csv'],
};

export function DesignFiles({
  designFiles,
  modules,
  canEdit,
  filterCategory,
  filterType,
  filterStage,
  filterVersion,
  onFilterCategoryChange,
  onFilterTypeChange,
  onFilterStageChange,
  onFilterVersionChange,
  onResetFilters,
  onAutoGenerate,
  onUpload,
  onSync,
  onDelete,
  onEditFile,
  onCreateSingle,
  onVersionUpdate,
}: DesignFilesProps) {
  const t = useThemeStyles();
  const { showToast } = useToast();
  const fileInputRef = useRef<HTMLInputElement>(null);

  const [uploadingDesignFile, setUploadingDesignFile] = useState<string | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [updatingVersionFileId, setUpdatingVersionFileId] = useState<string | null>(null);
  const [generateSuccess, setGenerateSuccess] = useState(false);

  const [showCreateModal, setShowCreateModal] = useState(false);
  const [createForm, setCreateForm] = useState({
    targetType: 'module' as 'module' | 'component',
    fileType: '装配图' as '装配图' | '配套表',
    targetId: '',
    searchTerm: '',
  });
  const [isCreating, setIsCreating] = useState(false);

  const [editingFile, setEditingFile] = useState<DesignFile | null>(null);
  const [editForm, setEditForm] = useState({
    name: '',
    stage: getDefaultStageForEntity('designFile'),
    version: '',
  });

  const [syncModalFile, setSyncModalFile] = useState<DesignFile | null>(null);
  const [syncModuleIds, setSyncModuleIds] = useState<string[]>([]);
  const [syncComponentIds, setSyncComponentIds] = useState<string[]>([]);
  const [isSyncing, setIsSyncing] = useState(false);
  const [syncProgress, setSyncProgress] = useState(0);
  const [syncErrors, setSyncErrors] = useState<string[]>([]);

  const [searchQuery, setSearchQuery] = useState('');

  const [filterTypeLocal, setFilterTypeLocal] = useState<'all' | 'assembly' | 'table'>('all');

  const filteredFiles = useMemo(() => {
    return designFiles.filter(df => {
      if (filterCategory === 'module' && df.category !== 'module') return false;
      if (filterCategory === 'component' && df.category !== 'component') return false;
      if (filterType === 'assembly' && df.type !== '装配图') return false;
      if (filterType === 'table' && df.type !== '配套表') return false;
      if (filterStage && df.stage !== filterStage) return false;
      if (filterVersion && df.version !== filterVersion) return false;
      if (searchQuery.trim()) {
        const query = searchQuery.toLowerCase();
        if (!df.name.toLowerCase().includes(query)) return false;
      }
      return true;
    });
  }, [designFiles, filterCategory, filterType, filterStage, filterVersion, searchQuery]);

  const filteredModules = useMemo(() => {
    if (!createForm.searchTerm) return modules;
    const term = createForm.searchTerm.toLowerCase();
    return modules.filter(m =>
      m.moduleName.toLowerCase().includes(term) ||
      m.moduleNumber.toLowerCase().includes(term)
    );
  }, [modules, createForm.searchTerm]);

  const handleSingleUpload = useCallback((e: React.ChangeEvent<HTMLInputElement>, designFileId: string) => {
    const file = e.target.files?.[0];
    if (file) {
      const ext = '.' + file.name.split('.').pop()?.toLowerCase();
      let valid = false;
      for (const extensions of Object.values(ACCEPTED_FORMATS)) {
        if (extensions.includes(ext)) {
          valid = true;
          break;
        }
      }
      if (!valid) {
        showToast(`不支持的文件格式。仅支持: ${Object.values(ACCEPTED_FORMATS).flat().join(', ')}`, 'error');
        return;
      }
      setUploadingDesignFile(designFileId);
      onUpload(e, designFileId);
      setTimeout(() => {
        setUploadingDesignFile(null);
        e.target.value = '';
      }, 1000);
    }
  }, [onUpload, showToast]);

  const handleAutoGenerate = useCallback(async () => {
    setIsGenerating(true);
    setGenerateSuccess(false);

    await new Promise(resolve => setTimeout(resolve, 500));

    onAutoGenerate();

    setIsGenerating(false);
    setGenerateSuccess(true);

    setTimeout(() => setGenerateSuccess(false), 3000);
  }, [onAutoGenerate]);

  const handleDownload = useCallback((file: DesignFile) => {
    if (file.data) {
      const blob = new Blob([file.data], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${file.name}.txt`;
      a.click();
      URL.revokeObjectURL(url);
      showToast('文件下载成功', 'success');
    }
  }, [showToast]);

  const handleVersionUpdate = useCallback((file: DesignFile) => {
    if (!canEdit) {
      showToast('您没有权限更新版本', 'error');
      return;
    }

    setUpdatingVersionFileId(file.id);
    showToast(`正在为 "${file.name}" 创建新版本...`, 'info');

    setTimeout(() => {
      if (onVersionUpdate) {
        onVersionUpdate(file);
      }
      setUpdatingVersionFileId(null);
      showToast(`已为 "${file.name}" 创建新版本`, 'success');
    }, 800);
  }, [canEdit, onVersionUpdate, showToast]);

  const handleOpenEditModal = useCallback((file: DesignFile) => {
    setEditingFile(file);
    setEditForm({
      name: file.name,
      stage: file.stage || '',
      version: file.version || '',
    });
  }, []);

  const handleCloseEditModal = useCallback(() => {
    setEditingFile(null);
    setEditForm({
      name: '',
      stage: getDefaultStageForEntity('designFile'),
      version: '',
    });
  }, []);

  const handleOpenSyncModal = useCallback((file: DesignFile) => {
    setSyncModalFile(file);
    setSyncModuleIds([]);
    setSyncComponentIds([]);
    setSyncErrors([]);
    setIsSyncing(false);
    setSyncProgress(0);
  }, []);

  const handleCloseSyncModal = useCallback(() => {
    if (!isSyncing) {
      setSyncModalFile(null);
      setSyncModuleIds([]);
      setSyncComponentIds([]);
      setSyncErrors([]);
      setSyncProgress(0);
    }
  }, [isSyncing]);

  const handleComponentSelect = useCallback((componentId: string, checked: boolean) => {
    setSyncComponentIds(prev =>
      checked ? [...prev, componentId] : prev.filter(id => id !== componentId)
    );
  }, []);

  const handleSelectAll = useCallback(() => {
    const fileName = syncModalFile?.name || '';
    const searchTerm = fileName.replace(/ 装配图| 配套表/g, '').trim();

    const matchingModules = modules.filter(m =>
      m.moduleName.toLowerCase().includes(searchTerm.toLowerCase()) ||
      searchTerm.toLowerCase().includes(m.moduleName.toLowerCase())
    ).map(m => m.id);

    const matchingComponents = modules.flatMap(m =>
      (m.components || []).filter(c =>
        c.componentName.toLowerCase().includes(searchTerm.toLowerCase()) ||
        searchTerm.toLowerCase().includes(c.componentName.toLowerCase())
      )
    ).map(c => c.id);

    const totalMatching = matchingModules.length + matchingComponents.length;
    const allSelected = totalMatching > 0 &&
      matchingModules.every(id => syncModuleIds.includes(id)) &&
      matchingComponents.every(id => syncComponentIds.includes(id));

    if (allSelected) {
      setSyncModuleIds([]);
      setSyncComponentIds([]);
    } else {
      setSyncModuleIds(matchingModules);
      setSyncComponentIds(matchingComponents);
    }
  }, [syncModalFile, syncModuleIds, syncComponentIds, modules]);

  const handleSync = useCallback(async () => {
    if (!syncModalFile) return;

    const totalCount = syncModuleIds.length + syncComponentIds.length;
    if (totalCount === 0) {
      showToast('请选择要同步的模块或组件', 'warning');
      return;
    }

    setIsSyncing(true);
    setSyncProgress(0);
    setSyncErrors([]);

    const allIds = [...syncModuleIds, ...syncComponentIds];
    const results: { id: string; success: boolean; error?: string }[] = [];
    let completedSteps = 0;

    for (const id of allIds) {
      try {
        await new Promise((resolve, reject) => {
          setTimeout(() => {
            const shouldFail = Math.random() < 0.05;
            if (shouldFail) {
              reject(new Error('同步失败'));
            } else {
              resolve(true);
            }
          }, 200);
        });
        results.push({ id, success: true });
      } catch (err) {
        results.push({ id, success: false, error: (err as Error).message });
      }
      completedSteps++;
      setSyncProgress(Math.round((completedSteps / allIds.length) * 100));
    }

    const failedIds = results.filter(r => !r.success).map(r => r.id);
    if (failedIds.length > 0) {
      setSyncErrors(failedIds);
    }

    const updatedFile: Partial<DesignFile> = {
      adaptedModuleIds: [...new Set([...(syncModalFile.adaptedModuleIds || []), ...syncModuleIds])],
      adaptedComponentIds: [...new Set([...(syncModalFile.adaptedComponentIds || []), ...syncComponentIds])],
    };

    if (onSync) {
      onSync({ ...syncModalFile, ...updatedFile } as DesignFile);
    }

    setIsSyncing(false);
    setSyncModalFile(null);
    setSyncModuleIds([]);
    setSyncComponentIds([]);
    setSyncErrors([]);
    setSyncProgress(0);

    const successCount = results.filter(r => r.success).length;
    if (failedIds.length > 0) {
      showToast(`同步完成: ${successCount} 成功, ${failedIds.length} 失败 (可重试)`, 'warning');
    } else {
      showToast(`成功同步 ${successCount} 个项目到 "${syncModalFile.name}"`, 'success');
    }
  }, [syncModalFile, syncModuleIds, syncComponentIds, onSync, showToast]);

  const handleRetryFailed = useCallback(() => {
    if (syncErrors.length === 0) return;

    const failedModuleIds = syncErrors.filter(id => syncModalFile?.adaptedModuleIds?.includes(id));
    const failedComponentIds = syncErrors.filter(id => syncModalFile?.adaptedComponentIds?.includes(id));

    setSyncModuleIds(prev => [...prev, ...failedModuleIds.filter(id => !prev.includes(id))]);
    setSyncComponentIds(prev => [...prev, ...failedComponentIds.filter(id => !prev.includes(id))]);
    setSyncErrors([]);

    handleSync();
  }, [syncErrors, syncModalFile, handleSync]);

  const handleSaveEdit = useCallback(() => {
    if (!editingFile) return;

    if (!editForm.name.trim()) {
      showToast('请输入文件名称', 'error');
      return;
    }

    if (!editForm.version.trim()) {
      showToast('请输入版本号', 'error');
      return;
    }

    const updatedFile: Partial<DesignFile> = {
      name: editForm.name,
      stage: editForm.stage,
      version: editForm.version,
    };

    if (onEditFile) {
      onEditFile({ ...editingFile, ...updatedFile } as DesignFile);
    }

    showToast('设计文件已更新', 'success');
    handleCloseEditModal();
  }, [editingFile, editForm, onEditFile, showToast, handleCloseEditModal]);

  const formatFileSize = (bytes?: number) => {
    if (!bytes) return '-';
    if (bytes < 1024) return bytes + ' B';
    if (bytes < 1024 * 1024) return (bytes / 1024).toFixed(1) + ' KB';
    return (bytes / (1024 * 1024)).toFixed(1) + ' MB';
  };

  const uniqueStages = useMemo(() => {
    const stages = new Set<string>();
    designFiles.forEach(f => { if (f.stage) stages.add(f.stage); });
    return Array.from(stages);
  }, [designFiles]);

  const uniqueVersions = useMemo(() => {
    const versions = new Set<string>();
    designFiles.forEach(f => { if (f.version) versions.add(f.version); });
    return Array.from(versions);
  }, [designFiles]);

  const stageInfo = useMemo(() => {
    const stageList = ['F阶段', 'C阶段', 'S阶段', 'D阶段', 'P阶段'];
    return stageList.map(stage => {
      const stageFiles = designFiles.filter(f => f.stage === stage);
      const assemblyCount = stageFiles.filter(f => f.type === '装配图').length;
      const tableCount = stageFiles.filter(f => f.type === '配套表').length;
      return { stage, assemblyCount, tableCount, total: stageFiles.length };
    });
  }, [designFiles]);

  const getStageButtonStyle = (stage: string, info: typeof stageInfo[0]) => {
    const isSelected = filterStage === stage;
    const isOtherSelected = !!filterStage && filterStage !== stage;
    const hasFiles = info.total > 0;

    const colors: Record<string, { active: string; light: string; dark: string; ring: string }> = {
      'F阶段': { active: 'bg-blue-500', light: 'bg-blue-100 border-blue-300', dark: 'text-blue-900', ring: 'ring-blue-400' },
      'C阶段': { active: 'bg-green-500', light: 'bg-green-100 border-green-300', dark: 'text-green-900', ring: 'ring-green-400' },
      'S阶段': { active: 'bg-yellow-500', light: 'bg-yellow-100 border-yellow-300', dark: 'text-yellow-900', ring: 'ring-yellow-400' },
      'D阶段': { active: 'bg-orange-500', light: 'bg-orange-100 border-orange-300', dark: 'text-orange-900', ring: 'ring-orange-400' },
      'P阶段': { active: 'bg-purple-500', light: 'bg-purple-100 border-purple-300', dark: 'text-purple-900', ring: 'ring-purple-400' },
    };

    const stageColors = colors[stage] || { active: 'bg-gray-500', light: 'bg-gray-100 border-gray-300', dark: 'text-gray-900', ring: 'ring-gray-400' };

    return {
      flex: isSelected ? '4' : isOtherSelected ? '0 0 5%' : '1',
      minWidth: isOtherSelected ? '0' : '80px',
      opacity: isOtherSelected ? 0.3 : 1,
      colors: stageColors,
      isSelected,
      hasFiles,
    };
  };

  const handleOpenCreateModal = () => {
    setCreateForm({
      targetType: 'module',
      fileType: '装配图',
      targetId: '',
      searchTerm: '',
    });
    setShowCreateModal(true);
  };

  const handleCreateDesign = useCallback(() => {
    if (!createForm.targetId) {
      showToast('请选择目标对象', 'warning');
      return;
    }

    setIsCreating(true);

    const format = createForm.fileType === '装配图' ? 'AutoCAD' : 'Excel';
    const category = createForm.targetType === 'module' ? 'module' : 'component';

    onCreateSingle({
      targetType: createForm.targetType,
      targetId: createForm.targetId,
      fileType: createForm.fileType,
      format,
    });

    setTimeout(() => {
      setIsCreating(false);
      setShowCreateModal(false);
      showToast('设计文件创建成功', 'success');
    }, 500);
  }, [createForm, onCreateSingle, showToast]);

  const selectedTarget = useMemo(() => {
    if (!createForm.targetId) return null;
    if (createForm.targetType === 'module') {
      return modules.find(m => m.id === createForm.targetId);
    }
    for (const module of modules) {
      const comp = module.components.find(c => c.id === createForm.targetId);
      if (comp) return { module, component: comp };
    }
    return null;
  }, [createForm.targetId, createForm.targetType, modules]);

  const renderCreateModal = () => {
    if (!showCreateModal) return null;

    return (
      <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50" onClick={() => setShowCreateModal(false)}>
        <div className={`bg-white rounded-lg p-6 w-full max-w-lg ${t.modalBg}`} onClick={(e) => e.stopPropagation()}>
          <div className="flex items-center justify-between mb-4">
            <h2 className={`text-xl font-semibold ${t.text}`}>新建设计文件</h2>
            <button onClick={() => setShowCreateModal(false)} className={`p-1.5 ${t.textMuted} hover:${t.text}`}>
              <X size={20} />
            </button>
          </div>

          <div className="space-y-4">
            <div>
              <label className={`block text-sm font-medium mb-2 ${t.textSecondary}`}>目标类型</label>
              <div className="flex gap-2">
                <button
                  onClick={() => setCreateForm(prev => ({ ...prev, targetType: 'module', targetId: '', searchTerm: '' }))}
                  className={`flex-1 px-4 py-2 rounded-lg border text-sm flex items-center justify-center gap-2 ${
                    createForm.targetType === 'module'
                      ? 'bg-blue-600 text-white border-blue-600'
                      : `${t.border} ${t.text}`
                  }`}
                >
                  <Layout size={16} />
                  模块
                </button>
                <button
                  onClick={() => setCreateForm(prev => ({ ...prev, targetType: 'component', targetId: '', searchTerm: '' }))}
                  className={`flex-1 px-4 py-2 rounded-lg border text-sm flex items-center justify-center gap-2 ${
                    createForm.targetType === 'component'
                      ? 'bg-green-600 text-white border-green-600'
                      : `${t.border} ${t.text}`
                  }`}
                >
                  <FileCode size={16} />
                  组件
                </button>
              </div>
            </div>

            <div>
              <label className={`block text-sm font-medium mb-2 ${t.textSecondary}`}>文件类型</label>
              <div className="flex gap-2">
                <button
                  onClick={() => setCreateForm(prev => ({ ...prev, fileType: '装配图' }))}
                  className={`flex-1 px-4 py-2 rounded-lg border text-sm flex items-center justify-center gap-2 ${
                    createForm.fileType === '装配图'
                      ? 'bg-purple-600 text-white border-purple-600'
                      : `${t.border} ${t.text}`
                  }`}
                >
                  <FileCode size={16} />
                  装配图 (AutoCAD)
                </button>
                <button
                  onClick={() => setCreateForm(prev => ({ ...prev, fileType: '配套表' }))}
                  className={`flex-1 px-4 py-2 rounded-lg border text-sm flex items-center justify-center gap-2 ${
                    createForm.fileType === '配套表'
                      ? 'bg-purple-600 text-white border-purple-600'
                      : `${t.border} ${t.text}`
                  }`}
                >
                  <Table size={16} />
                  配套表 (Excel)
                </button>
              </div>
            </div>

            <div>
              <label className={`block text-sm font-medium mb-2 ${t.textSecondary}`}>
                选择 {createForm.targetType === 'module' ? '模块' : '组件'}
              </label>
              <div className="relative mb-2">
                <Search size={16} className={`absolute left-3 top-1/2 -translate-y-1/2 ${t.textMuted}`} />
                <input
                  type="text"
                  value={createForm.searchTerm}
                  onChange={(e) => setCreateForm(prev => ({ ...prev, searchTerm: e.target.value }))}
                  placeholder={`搜索${createForm.targetType === 'module' ? '模块' : '组件'}...`}
                  className={`w-full pl-10 pr-4 py-2 border rounded-lg ${t.input}`}
                />
              </div>

              <div className={`border rounded-lg max-h-48 overflow-y-auto ${t.border}`}>
                {createForm.targetType === 'module' ? (
                  filteredModules.length === 0 ? (
                    <div className={`p-4 text-center ${t.textMuted}`}>未找到模块</div>
                  ) : (
                    filteredModules.map(module => (
                      <button
                        key={module.id}
                        onClick={() => setCreateForm(prev => ({ ...prev, targetId: module.id }))}
                        className={`w-full px-4 py-2 text-left flex items-center gap-2 ${
                          createForm.targetId === module.id ? 'bg-blue-50 dark:bg-blue-900/30' : ''
                        } hover:${t.hoverBg} border-b last:border-b-0 ${t.border}`}
                      >
                        <Layout size={14} className={t.textMuted} />
                        <div className="flex-1 min-w-0">
                          <div className={`text-sm font-medium truncate ${t.text}`}>{module.moduleName}</div>
                          <div className={`text-xs ${t.textMuted}`}>{module.moduleNumber} | {module.category}</div>
                        </div>
                        {createForm.targetId === module.id && (
                          <CheckCircle size={16} className="text-blue-500" />
                        )}
                      </button>
                    ))
                  )
                ) : (
                  modules.flatMap(module => {
                    const components = module.components || [];
                    const filtered = createForm.searchTerm
                      ? components.filter(c =>
                          c.componentName.toLowerCase().includes(createForm.searchTerm.toLowerCase()) ||
                          c.componentNumber.toLowerCase().includes(createForm.searchTerm.toLowerCase())
                        )
                      : components;

                    if (filtered.length === 0) return [];

                    return filtered.map(comp => (
                      <button
                        key={comp.id}
                        onClick={() => setCreateForm(prev => ({ ...prev, targetId: comp.id }))}
                        className={`w-full px-4 py-2 text-left flex items-center gap-2 ${
                          createForm.targetId === comp.id ? 'bg-green-50 dark:bg-green-900/30' : ''
                        } hover:${t.hoverBg} border-b last:border-b-0 ${t.border}`}
                      >
                        <FileCode size={14} className={t.textMuted} />
                        <div className="flex-1 min-w-0">
                          <div className={`text-sm font-medium truncate ${t.text}`}>{comp.componentName}</div>
                          <div className={`text-xs ${t.textMuted}`}>{comp.componentNumber} | {module.moduleName}</div>
                        </div>
                        {createForm.targetId === comp.id && (
                          <CheckCircle size={16} className="text-green-500" />
                        )}
                      </button>
                    ));
                  })
                )}
              </div>
            </div>

            {selectedTarget && (
              <div className={`p-4 rounded-lg ${t.emptyBg}`}>
                <div className="text-xs text-center mb-2">已选择</div>
                <div className="text-sm font-medium text-center">
                  {createForm.targetType === 'module'
                    ? (selectedTarget as Module).moduleName
                    : (selectedTarget as { module: Module; component: Component }).component.componentName}
                </div>
                <div className={`text-xs text-center mt-1 ${t.textMuted}`}>
                  将创建: {createForm.fileType} ({createForm.fileType === '装配图' ? 'AutoCAD' : 'Excel'})
                </div>
              </div>
            )}
          </div>

          <div className="mt-6 flex justify-end gap-3">
            <button
              onClick={() => setShowCreateModal(false)}
              className={`px-4 py-2 border rounded-lg ${t.border} ${t.text} hover:${t.hoverBg}`}
            >
              取消
            </button>
            <button
              onClick={handleCreateDesign}
              disabled={!createForm.targetId || isCreating}
              className={`px-4 py-2 rounded-lg flex items-center gap-2 ${
                createForm.targetId && !isCreating
                  ? 'bg-purple-600 text-white hover:bg-purple-700'
                  : 'bg-gray-300 text-gray-500 cursor-not-allowed'
              }`}
            >
              {isCreating ? (
                <>
                  <Loader2 size={16} className="animate-spin" />
                  创建中...
                </>
              ) : (
                <>
                  <Plus size={16} />
                  创建
                </>
              )}
            </button>
          </div>
        </div>
      </div>
    );
  };

  const renderEditModal = () => {
    if (!editingFile) return null;

    const isModuleFile = editingFile.category === 'module';

    return (
      <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50" onClick={handleCloseEditModal}>
        <div className={`bg-white rounded-lg p-6 w-full max-w-lg ${t.modalBg}`} onClick={(e) => e.stopPropagation()}>
          <div className="flex items-center justify-between mb-4">
            <h2 className={`text-xl font-semibold ${t.text}`}>
              编辑设计文件
              <span className={`ml-2 text-sm font-normal ${t.textMuted}`}>
                ({isModuleFile ? '模块' : '组件'} - {editingFile.type})
              </span>
            </h2>
            <button onClick={handleCloseEditModal} className={`p-1.5 ${t.textMuted} hover:${t.text}`}>
              <X size={20} />
            </button>
          </div>

          <div className="space-y-4">
            <div>
              <label className={`block text-sm font-medium mb-2 ${t.textSecondary}`}>文件名称 *</label>
              <input
                type="text"
                value={editForm.name}
                onChange={(e) => setEditForm(prev => ({ ...prev, name: e.target.value }))}
                className={`w-full px-3 py-2 border rounded-lg ${t.input}`}
                placeholder="请输入文件名称"
              />
            </div>

            <div>
              <label className={`block text-sm font-medium mb-2 ${t.textSecondary}`}>所属阶段</label>
              <select
                value={editForm.stage}
                onChange={(e) => setEditForm(prev => ({ ...prev, stage: e.target.value }))}
                className={`w-full px-3 py-2 border rounded-lg ${t.input}`}
              >
                <option value="">请选择阶段</option>
                <option value="F阶段">F阶段</option>
                <option value="C阶段">C阶段</option>
                <option value="S阶段">S阶段</option>
                <option value="D阶段">D阶段</option>
                <option value="P阶段">P阶段</option>
              </select>
            </div>

            <div>
              <label className={`block text-sm font-medium mb-2 ${t.textSecondary}`}>版本号 *</label>
              <input
                type="text"
                value={editForm.version}
                onChange={(e) => setEditForm(prev => ({ ...prev, version: e.target.value }))}
                className={`w-full px-3 py-2 border rounded-lg ${t.input}`}
                placeholder="如：A版"
              />
            </div>
          </div>

          <div className="mt-6 flex justify-end gap-3">
            <button
              onClick={handleCloseEditModal}
              className={`px-4 py-2 border rounded-lg ${t.border} ${t.text} hover:${t.hoverBg}`}
            >
              取消
            </button>
            <button
              onClick={handleSaveEdit}
              className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700"
            >
              保存修改
            </button>
          </div>
        </div>
      </div>
    );
  };

  const renderSyncModal = () => {
    if (!syncModalFile) return null;

    const fileName = syncModalFile.name || '';
    const searchTerm = fileName.replace(/ 装配图| 配套表/g, '').trim();
    const isModuleFile = syncModalFile.category === 'module';

    const matchingModules = modules.filter(m =>
      m.moduleName.toLowerCase().includes(searchTerm.toLowerCase()) ||
      searchTerm.toLowerCase().includes(m.moduleName.toLowerCase())
    );

    const matchingComponents = modules.flatMap(m =>
      (m.components || []).filter(c =>
        c.componentName.toLowerCase().includes(searchTerm.toLowerCase()) ||
        searchTerm.toLowerCase().includes(c.componentName.toLowerCase())
      )
    );

    const displayModules = isModuleFile ? matchingModules : [];
    const displayComponents = isModuleFile ? [] : matchingComponents;
    const totalMatching = displayModules.length + displayComponents.length;

    const allSelected = totalMatching > 0 &&
      displayModules.every(m => syncModuleIds.includes(m.id)) &&
      displayComponents.every(c => syncComponentIds.includes(c.id));
    const someSelected = displayModules.some(m => syncModuleIds.includes(m.id)) ||
      displayComponents.some(c => syncComponentIds.includes(c.id));

    const selectedCount = syncModuleIds.length + syncComponentIds.length;

    return (
      <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50" onClick={handleCloseSyncModal}>
        <div className={`bg-white rounded-lg p-6 w-full max-w-2xl max-h-[80vh] overflow-hidden flex flex-col ${t.modalBg}`} onClick={(e) => e.stopPropagation()}>
          <div className="flex items-center justify-between mb-4">
            <div>
              <h2 className={`text-xl font-semibold ${t.text}`}>同步{isModuleFile ? '模块' : '组件'}</h2>
              <p className={`text-sm ${t.textMuted} mt-1`}>
                文件: {syncModalFile.name} | 类型: {syncModalFile.category} | 找到 {displayModules.length} 个模块, {displayComponents.length} 个组件
              </p>
            </div>
            <button onClick={handleCloseSyncModal} className={`p-1.5 ${t.textMuted} hover:${t.text}`}>
              <X size={20} />
            </button>
          </div>

          <div className={`flex items-center gap-3 mb-4 px-3 py-2 rounded-lg ${t.emptyBg}`}>
            <label className="flex items-center gap-2 cursor-pointer">
              <input
                type="checkbox"
                checked={allSelected}
                ref={(el) => { if (el) el.indeterminate = !allSelected && someSelected; }}
                onChange={handleSelectAll}
                className="rounded"
              />
              <span className={`text-sm font-medium ${t.text}`}>全选/取消全选</span>
            </label>
            <span className={`text-sm ${t.textMuted}`}>
              已选择: {selectedCount} 个项目
            </span>
          </div>

          <div className={`flex-1 overflow-auto border rounded-lg ${t.border}`}>
            {totalMatching === 0 ? (
              <div className={`p-8 text-center ${t.textMuted}`}>
                <FileCode size={48} className={`mx-auto mb-4 opacity-50`} />
                <p>未找到与 "{searchTerm}" 匹配{isModuleFile ? '的模块' : '的组件'}</p>
                <p className="text-xs mt-2">尝试调整文件名后再试</p>
              </div>
            ) : (
              <>
                {displayModules.length > 0 && (
                  <div className={`px-4 py-2 bg-blue-50 dark:bg-blue-900/20 border-b ${t.border}`}>
                    <span className={`text-sm font-medium text-blue-700 dark:text-blue-300`}>模块 ({displayModules.length})</span>
                  </div>
                )}
                {displayModules.map(m => (
                  <label
                    key={m.id}
                    className={`flex items-center gap-3 px-4 py-3 cursor-pointer hover:${t.hoverBg} border-b last:border-b-0 ${t.border}`}
                  >
                    <input
                      type="checkbox"
                      checked={syncModuleIds.includes(m.id)}
                      onChange={() => {
                        const checked = !syncModuleIds.includes(m.id);
                        setSyncModuleIds(prev => checked ? [...prev, m.id] : prev.filter(id => id !== m.id));
                      }}
                      className="rounded"
                    />
                    <Layout size={16} className="text-blue-500" />
                    <div className="flex-1 min-w-0">
                      <div className={`text-sm font-medium ${t.text}`}>{m.moduleName}</div>
                      <div className={`text-xs ${t.textMuted}`}>{m.moduleNumber} | {m.category}</div>
                    </div>
                    <span className={`px-2 py-0.5 rounded text-xs ${
                      m.status === '已发布' ? 'bg-green-100 text-green-700' :
                      m.status === '开发中' ? 'bg-yellow-100 text-yellow-700' :
                      'bg-gray-100 text-gray-700'
                    }`}>
                      {m.status}
                    </span>
                  </label>
                ))}

                {displayComponents.length > 0 && (
                  <div className={`px-4 py-2 bg-green-50 dark:bg-green-900/20 border-b ${t.border}`}>
                    <span className={`text-sm font-medium text-green-700 dark:text-green-300`}>组件 ({displayComponents.length})</span>
                  </div>
                )}
                {displayComponents.map(comp => {
                  const module = modules.find(m => m.components?.some((c: any) => c.id === comp.id));
                  return (
                    <label
                      key={comp.id}
                      className={`flex items-center gap-3 px-4 py-3 cursor-pointer hover:${t.hoverBg} border-b last:border-b-0 ${t.border}`}
                    >
                      <input
                        type="checkbox"
                        checked={syncComponentIds.includes(comp.id)}
                        onChange={() => {
                          const checked = !syncComponentIds.includes(comp.id);
                          setSyncComponentIds(prev => checked ? [...prev, comp.id] : prev.filter(id => id !== comp.id));
                        }}
                        className="rounded"
                      />
                      <FileCode size={16} className="text-green-500" />
                      <div className="flex-1 min-w-0">
                        <div className={`text-sm font-medium ${t.text}`}>{comp.componentName}</div>
                        <div className={`text-xs ${t.textMuted}`}>
                          {comp.componentNumber} | {module?.moduleName || '未知模块'}
                        </div>
                      </div>
                      <span className={`px-2 py-0.5 rounded text-xs ${
                        comp.status === '已发布' ? 'bg-green-100 text-green-700' :
                        comp.status === '开发中' ? 'bg-yellow-100 text-yellow-700' :
                        'bg-gray-100 text-gray-700'
                      }`}>
                        {comp.status}
                      </span>
                    </label>
                  );
                })}
              </>
            )}
          </div>

          {isSyncing && (
            <div className="mt-4">
              <div className="flex items-center justify-between mb-2">
                <span className={`text-sm ${t.text}`}>同步进度</span>
                <span className={`text-sm ${t.textMuted}`}>{syncProgress}%</span>
              </div>
              <div className="w-full h-2 bg-gray-200 rounded-full overflow-hidden">
                <div
                  className="h-full bg-blue-600 transition-all duration-300"
                  style={{ width: `${syncProgress}%` }}
                />
              </div>
            </div>
          )}

          {syncErrors.length > 0 && !isSyncing && (
            <div className={`mt-4 p-3 rounded-lg bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800`}>
              <div className="flex items-center justify-between">
                <span className={`text-sm text-red-700 dark:text-red-300`}>
                  {syncErrors.length} 个项目同步失败
                </span>
                <button
                  onClick={handleRetryFailed}
                  className="px-3 py-1 text-xs bg-red-100 dark:bg-red-900/50 text-red-700 dark:text-red-300 rounded hover:bg-red-200 dark:hover:bg-red-900/70"
                >
                  重试
                </button>
              </div>
            </div>
          )}

          <div className="mt-4 flex justify-end gap-3">
            <button
              onClick={handleCloseSyncModal}
              disabled={isSyncing}
              className={`px-4 py-2 border rounded-lg ${t.border} ${t.text} hover:${t.hoverBg} disabled:opacity-50`}
            >
              {isSyncing ? '同步中...' : '取消'}
            </button>
            <button
              onClick={handleSync}
              disabled={isSyncing || selectedCount === 0}
              className={`px-4 py-2 rounded-lg flex items-center gap-2 ${
                isSyncing || selectedCount === 0
                  ? 'bg-gray-300 text-gray-500 cursor-not-allowed'
                  : 'bg-blue-600 text-white hover:bg-blue-700'
              }`}
            >
              {isSyncing && <Loader2 size={16} className="animate-spin" />}
              {isSyncing ? `同步中 (${syncProgress}%)` : `同步 (${selectedCount})`}
            </button>
          </div>
        </div>
      </div>
    );
  };

  if (designFiles.length === 0) {
    return (
      <div className="space-y-4">
        <div className={`${t.card} rounded-lg shadow-sm border ${t.border} p-4`}>
          <div className="flex flex-wrap items-center gap-4 mb-4">
            <div className="flex items-center gap-2">
              <div className="relative">
                <Search className={`absolute left-3 top-1/2 -translate-y-1/2 ${t.textMuted}`} size={16} />
                <input
                  type="text"
                  placeholder="搜索文件..."
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                  className={`pl-10 pr-4 py-2 border rounded-lg text-sm w-48 ${t.input}`}
                />
              </div>
            </div>
            <div className="flex items-center gap-2 ml-auto">
              {canEdit && (
                <button
                  onClick={handleAutoGenerate}
                  disabled={isGenerating}
                  className={`flex items-center gap-2 px-4 py-2 rounded-lg text-white transition-all ${
                    generateSuccess
                      ? 'bg-green-600 hover:bg-green-700'
                      : isGenerating
                      ? 'bg-blue-400 cursor-wait'
                      : 'bg-gradient-to-r from-blue-600 to-purple-600 hover:from-blue-700 hover:to-purple-700'
                  }`}
                >
                  {isGenerating ? (
                    <>
                      <Loader2 size={18} className="animate-spin" />
                      生成中...
                    </>
                  ) : generateSuccess ? (
                    <>
                      <CheckCircle size={18} />
                      生成成功
                    </>
                  ) : (
                    <>
                      <Sparkles size={18} />
                      自动生成
                    </>
                  )}
                </button>
              )}
              {canEdit && (
                <button
                  onClick={handleOpenCreateModal}
                  className={`flex items-center gap-2 px-4 py-2 bg-purple-600 text-white rounded-lg hover:bg-purple-700`}
                >
                  <Plus size={18} />
                  新增
                </button>
              )}
            </div>
          </div>
        </div>

        <div className={`text-center py-12 ${t.card} rounded-lg border ${t.border}`}>
          <FileText className={`mx-auto ${t.textMuted} mb-4`} size={48} />
          <p className={t.textMuted}>暂无设计文件</p>
          {canEdit && (
            <p className={`text-sm ${t.textMuted} mt-2`}>
              点击"自动生成"创建设计图表，或"新增"添加特定模块/组件的设计文件
            </p>
          )}
        </div>

        {showCreateModal && renderCreateModal()}
        {editingFile && renderEditModal()}
        {syncModalFile && renderSyncModal()}
      </div>
    );
  }

  return (
    <div className="space-y-4 w-full">
      <div className="flex gap-1 h-20 w-full">
        {stageInfo.map(({ stage, assemblyCount, tableCount, total }) => {
          const style = getStageButtonStyle(stage, { stage, assemblyCount, tableCount, total });
          return (
            <button
              key={stage}
              onClick={() => {
                onFilterStageChange(style.isSelected ? '' : stage);
              }}
              style={{
                flex: style.flex,
                minWidth: style.minWidth,
                opacity: style.opacity,
                transition: 'flex 500ms ease-out, opacity 300ms ease-out, min-width 500ms ease-out',
              }}
              className={`
                relative rounded-lg border-2 overflow-hidden
                ${style.isSelected
                  ? `backdrop-blur-sm ${style.colors.light} shadow-lg ring-2 ring-offset-1 ${style.colors.ring}`
                  : style.hasFiles
                    ? 'backdrop-blur-sm border-gray-300/50 bg-white/30 hover:bg-white/50'
                    : 'backdrop-blur-sm border-gray-200/30 bg-gray-50/30 hover:bg-gray-100/50'
                }
              `}
            >
              <div className={`h-full flex flex-col justify-center px-2 ${style.isSelected ? style.colors.light : ''}`}>
                <div className={`text-sm font-bold text-center mb-1 ${style.isSelected ? style.colors.dark : 'text-gray-900'}`}>
                  {stage}
                </div>
                {total > 0 && (
                  <div className="w-full h-3 bg-white/40 rounded-full overflow-hidden shadow-inner border border-gray-200/30">
                    <div
                      className={`h-full ${style.isSelected ? style.colors.active : 'bg-gray-400'} rounded-full`}
                      style={{ width: '100%', transition: 'background-color 300ms ease-out' }}
                    />
                  </div>
                )}
                <div className={`text-xs text-center mt-1 ${style.isSelected ? style.colors.dark : 'text-gray-500'}`}>
                  {assemblyCount}图/{tableCount}表
                </div>
                {style.isSelected && (
                  <div className={`absolute -top-0.5 left-1/2 -translate-x-1/2 w-3 h-3 rotate-45 ${style.colors.light} border-2 border-r-0 border-b-0 ${style.colors.dark}`} />
                )}
              </div>
            </button>
          );
        })}
      </div>

      <div className={`${t.card} rounded-lg shadow-sm border ${t.border} p-4`}>
        <div className="flex flex-wrap items-center gap-4 mb-4">
          <div className="flex items-center gap-2">
            <div className="relative">
              <Search className={`absolute left-3 top-1/2 -translate-y-1/2 ${t.textMuted}`} size={16} />
              <input
                type="text"
                placeholder="搜索文件..."
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className={`pl-10 pr-10 py-2 border rounded-lg text-sm w-64 focus:outline-none focus:ring-2 focus:ring-primary-500 ${t.input}`}
              />
              {searchQuery && (
                <button
                  onClick={() => setSearchQuery('')}
                  className={`absolute right-3 top-1/2 -translate-y-1/2 ${t.textMuted} hover:${t.text}`}
                >
                  <X size={14} />
                </button>
              )}
            </div>
            {searchQuery && (
              <span className={`text-sm ${t.textMuted}`}>
                找到 {filteredFiles.length} 个结果
              </span>
            )}
          </div>

          <div className="flex items-center gap-2">
            <select
              value={filterCategory}
              onChange={(e) => onFilterCategoryChange(e.target.value as 'all' | 'module' | 'component')}
              className={`px-3 py-2 border rounded-lg text-sm ${t.input}`}
            >
              <option value="all">全部分类</option>
              <option value="module">模块</option>
              <option value="component">组件</option>
            </select>

            <select
              value={filterVersion}
              onChange={(e) => onFilterVersionChange(e.target.value)}
              className={`px-3 py-2 border rounded-lg text-sm ${t.input}`}
            >
              <option value="">全部版本</option>
              {uniqueVersions.map(version => (
                <option key={version} value={version}>{version}</option>
              ))}
            </select>

            <select
              value={filterType}
              onChange={(e) => onFilterTypeChange(e.target.value as 'all' | 'assembly' | 'table')}
              className={`px-3 py-2 border rounded-lg text-sm ${t.input}`}
            >
              <option value="all">全部类型</option>
              <option value="assembly">装配图</option>
              <option value="table">配套表</option>
            </select>

            <button
              onClick={onResetFilters}
              className={`px-3 py-2 text-sm ${t.textMuted} hover:${t.text}`}
            >
              重置
            </button>
          </div>

          <div className="flex items-center gap-2 ml-auto">
            {canEdit && (
              <button
                onClick={handleAutoGenerate}
                disabled={isGenerating}
                className={`flex items-center gap-2 px-4 py-2 rounded-lg text-white transition-all ${
                  generateSuccess
                    ? 'bg-green-600 hover:bg-green-700'
                    : isGenerating
                    ? 'bg-blue-400 cursor-wait'
                    : 'bg-gradient-to-r from-blue-600 to-purple-600 hover:from-blue-700 hover:to-purple-700'
                }`}
              >
                {isGenerating ? (
                  <>
                    <Loader2 size={18} className="animate-spin" />
                    生成中...
                  </>
                ) : generateSuccess ? (
                  <>
                    <CheckCircle size={18} />
                    生成成功
                  </>
                ) : (
                  <>
                    <Sparkles size={18} />
                    自动生成
                  </>
                )}
              </button>
            )}
            {canEdit && (
              <button
                onClick={handleOpenCreateModal}
                className={`flex items-center gap-2 px-4 py-2 bg-purple-600 text-white rounded-lg hover:bg-purple-700`}
              >
                <Plus size={18} />
                新增
              </button>
            )}
          </div>
        </div>

        {filteredFiles.length === 0 && searchQuery && (
          <div className={`text-center py-8 ${t.textMuted}`}>
            <Search className={`mx-auto mb-2`} size={32} />
            <p>未找到匹配的文件</p>
            <p className="text-sm mt-1">尝试调整搜索条件或关键词</p>
          </div>
        )}

        {filteredFiles.length > 0 && (
          <table className="w-full">
            <thead className={t.tableHeader}>
              <tr>
                <th className={`px-4 py-3 text-left text-sm font-medium ${t.textSecondary}`}>文件名称</th>
                <th className={`px-4 py-3 text-left text-sm font-medium ${t.textSecondary}`}>类型</th>
                <th className={`px-4 py-3 text-left text-sm font-medium ${t.textSecondary}`}>格式</th>
                <th className={`px-4 py-3 text-left text-sm font-medium ${t.textSecondary}`}>分类</th>
                <th className={`px-4 py-3 text-left text-sm font-medium ${t.textSecondary}`}>阶段</th>
                <th className={`px-4 py-3 text-left text-sm font-medium ${t.textSecondary}`}>版本</th>
                <th className={`px-4 py-3 text-left text-sm font-medium ${t.textSecondary}`}>大小</th>
                <th className={`px-4 py-3 text-left text-sm font-medium ${t.textSecondary}`}>时间</th>
                <th className={`px-4 py-3 text-left text-sm font-medium ${t.textSecondary}`}>操作</th>
              </tr>
            </thead>
            <tbody>
              {filteredFiles.map((file) => (
                <tr key={file.id} className={`border-t ${t.border} ${t.hoverBg}`}>
                  <td className={`px-4 py-3 ${t.text}`}>{file.name}</td>
                  <td className={`px-4 py-3 ${t.text}`}>
                    <span className={`px-2 py-1 rounded text-xs ${
                      file.type === '装配图' ? 'bg-purple-100 text-purple-700' : 'bg-indigo-100 text-indigo-700'
                    }`}>
                      {file.type}
                    </span>
                  </td>
                  <td className={`px-4 py-3 ${t.textSecondary}`}>
                    <span className={`px-2 py-1 rounded text-xs ${
                      file.format === 'Excel' ? 'bg-green-100 text-green-700' :
                      file.format === 'AutoCAD' ? 'bg-orange-100 text-orange-700' :
                      'bg-red-100 text-red-700'
                    }`}>
                      {file.format}
                    </span>
                  </td>
                  <td className={`px-4 py-3 ${t.textSecondary}`}>
                    {file.category === 'module' ? '模块' : '组件'}
                  </td>
                  <td className={`px-4 py-3 ${t.textSecondary}`}>{file.stage || '-'}</td>
                  <td className={`px-4 py-3 ${t.textSecondary}`}>{file.version || '-'}</td>
                  <td className={`px-4 py-3 ${t.textSecondary}`}>{formatFileSize(file.fileSize)}</td>
                  <td className={`px-4 py-3 ${t.textSecondary}`}>{file.uploadDate.split(' ')[0]}</td>
                  <td className="px-4 py-3">
                    <div className="flex items-center gap-1">
                      <button
                        onClick={() => handleVersionUpdate(file)}
                        disabled={updatingVersionFileId === file.id || !canEdit}
                        className={`p-1.5 rounded hover:bg-gray-100 dark:hover:bg-gray-700 ${
                          updatingVersionFileId === file.id ? 'text-blue-500 animate-spin' : t.textMuted
                        }`}
                        title="版本更新"
                      >
                        {updatingVersionFileId === file.id ? (
                          <Loader2 size={16} />
                        ) : (
                          <FileSearch size={16} />
                        )}
                      </button>
                      <button
                        onClick={() => handleOpenEditModal(file)}
                        className={`p-1.5 rounded hover:bg-gray-100 dark:hover:bg-gray-700 ${t.textMuted}`}
                        title="编辑"
                      >
                        <Edit2 size={16} />
                      </button>
                      <button
                        onClick={() => handleOpenSyncModal(file)}
                        className={`p-1.5 rounded hover:bg-gray-100 dark:hover:bg-gray-700 ${t.textMuted}`}
                        title="同步"
                      >
                        <RefreshCw size={16} />
                      </button>
                      <label className={`p-1.5 rounded hover:bg-gray-100 dark:hover:bg-gray-700 ${t.textMuted} cursor-pointer`} title="上传">
                        <Upload size={16} />
                        {uploadingDesignFile === file.id && <RefreshCw size={14} className="animate-spin" />}
                        <input
                          type="file"
                          className="hidden"
                          accept=".dwg,.dxf,.dwt,.dws,.xlsx,.xls,.csv"
                          onChange={(e) => handleSingleUpload(e, file.id)}
                        />
                      </label>
                      <button
                        onClick={() => handleDownload(file)}
                        className={`p-1.5 rounded hover:bg-gray-100 dark:hover:bg-gray-700 ${t.textMuted}`}
                        title="下载"
                      >
                        <Download size={16} />
                      </button>
                      {canEdit && (
                        <button
                          onClick={() => {
                            if (confirm('确定要删除这个设计文件吗？')) {
                              onDelete(file.id);
                              showToast('设计文件已删除', 'success');
                            }
                          }}
                          className={`p-1.5 rounded hover:bg-gray-100 dark:hover:bg-gray-700 ${t.textMuted}`}
                          title="删除"
                        >
                          <Trash2 size={16} />
                        </button>
                      )}
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </div>

      {showCreateModal && renderCreateModal()}
      {editingFile && renderEditModal()}
      {syncModalFile && renderSyncModal()}
    </div>
  );
}

export default DesignFiles;